config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'argosui#index'

  get 'argosui/home'

  get 'argosui/inspection'

  get 'argosui/daily'

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/argosui_controller.rb
class ArgosuiController < ApplicationController
  def index
  end

  def home
  end

  def inspection
  end

  def daily
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/argosui_helper.rb
module ArgosuiHelper
end

app/views/argosui/home.html.erb
<h1>Argosui#home</h1>
<p>Find me in app/views/argosui/home.html.erb</p>

app/views/argosui/index.html.erb
<h1>Argosui#index</h1>
<p>Find me in app/views/argosui/index.html.erb</p>

app/views/argosui/inspection.html.erb
   <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="container">
    
    <div class="Start">
         <div class="row">
          
    <div class="col-md-4">
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <input id="email" type="text" maxlength="8"style="width: 2x"class="form-control" name="email" placeholder="User Name">
        </div>
     </div>
      
    <div class="col-md-4"> 
      <div class="row">
         <div class="col-lg-12">
            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Region <span class="caret"></span></button>
                <ul class="dropdown-menu scrollable-menu" role="menu" >
                    <li><a href="#">DFW</a></li>
                    <li><a href="#">Dallas</a></li>
                    <li><a href="#">Arkansas</a></li>
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                </ul>
             </div>
          </div>
        </div>
    </div>
             
             
        
    <div class="col-md-4">
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-date"></i></span>
                <input id="date" type="text" maxlength="15"style="width: 2x"class="form-control" name="date" placeholder="Date">
        </div>
    </div>
    
    
    
        </div>
    </div>
    
    
    
     
    <div class="row">
        <div class="col-md-6">
            <h2>Plants</h2>
                <div class="scrollable">
                    <table class="table table-striped table-bordered">
                        <thead><tr><th>State</th><th>Region</th><th>Plant Name</th></tr></thead>
                            <tbody>
                                  <tr><td>TX</td><td>DFW</td><td>100</td></tr>
                                  <tr><td>TX</td><td>DFW</td><td>101</td></tr>
                                  <tr><td>TX</td><td>Al</td><td>103</td></tr>
                                  <tr><td>TX</td><td>Me</td><td>104</td></tr>
                                  <tr><td>TX</td><td>Dal</td><td>105</td></tr>
                                  <tr><td>TX</td><td>Fr</td><td>106</td></tr>
                                  <tr><td>TX</td><td>Ir</td><td>107</td></tr>
                                  <tr><td>TX</td><td>Fri</td><td>108</td></tr>
                                  <tr><td>TX</td><td>Co</td><td>109</td></tr>
                                  <tr><td>AK</td><td>NLR</td><td>110</td></tr> 
                                  <tr><td>AK</td><td>Al</td><td>111</td></tr>
                                  <tr><td>AK</td><td>JS</td><td>112</td></tr>
                                  <tr><td>AK</td><td>LR</td><td>113</td></tr>
                                  <tr><td>AK</td><td>Ben</td><td>114</td></tr>
                                  <tr><td>AK</td><td>Ca</td><td>115</td></tr>
                            </tbody>
                    </table>
                </div>
        </div>
                    
        <div class="col-md-6">
            <h2>Inspections</h2>
                <p></p>
                <p></p>
         
                <button type="button" class="btn btn-primary"><%= link_to "Daily", argosui_daily_path %></button></br>
                <p></p>
                <p></p>
                <button type="button" class="btn btn-primary">Monthly</button>
                <button type="button" class="btn btn-primary">Mthly UST Rectfr</button> 
                <button type="button" class="btn btn-primary">Mthly  UST Spill</button>
                <button type="button" class="btn btn-primary">Mthly Spill Logs</button></br>
                <p></p>
                <p></p>
                <button type="button" class="btn btn-primary">Quarterly-Visual</button>
                <button type="button" class="btn btn-primary">Qtr-Shop-Inspection</button>
                
        </div>
    </div>
                    
                </div>

app/views/layouts/_nav.html.erb
<div id="wrapper">

        <!-- Sidebar -->
        
        <div id="sidebar-wrapper"> 
            <ul class="sidebar-nav">
                <li >
                    <a href="#">
                      <i class="fa fa-times"></i>
                    </a>
                </li>
                 <li >
                    <a href="#">
                        ARGOS RMX SC
                    </a>
                </li>
                <li>
                    <a href="#">Inspection</a>
                </li>       
		        <li >
                    <a href="#" class="sidebar-menu-button" data-toggle="sidebar-collapse">
				    User
			         </a>

			<!-- Submenu -->
			             <ul class="sidebar-submenu sm-condensed">
				            <li class="sidebar-menu-item">
					           <a href="#" class="sidebar-menu-button">User Group</a>
				            </li>
				            <li class="sidebar-menu-item">
					           <a href="#" class="sidebar-menu-button">User Search</a>
				            </li>
				
			             </ul>
                </li>
                
                <li >
                    <a href="#" class="sidebar-menu-button" data-toggle="sidebar-collapse">
				    Company
			         </a> 
			
			<!-- Submenu -->
			             <ul class="sidebar-submenu sm-condensed">
                             <li class="sidebar-menu-item">
                                <a href="#" class="sidebar-menu-button">Modules</a>
				            </li>
				            <li class="sidebar-menu-item">
                                <a href="#" class="sidebar-menu-button">ARGOS Videos</a>
				            </li>
				
			             </ul>
                </li>
				<li>
                    <a href="#">Maintenance</a>
                </li>
				
                <li>
                    <a href="#">Assessment Reports</a>
                </li>
               
            </ul>
        </div>
        
         <!-- Navbar-->
         <nav class="navbar navbar-inverse">
             <div id="navwrapper">
                <div class="container-fluid">
                    <div class="nav navbar-nav navbar-left">          
                        <a id="menu-toggle" href="#" class="btn btn-default btn-md toggle"><i class="fa fa-bars" aria-hidden="true"></i>Menu</a>
                    </div>
                            <ul class="nav navbar-nav navbar-right">
                                <!--<li><a href="#">Home</a></li>-->
                                <li><%= link_to "Home", argosui_home_path %></li>
                                <li><%= link_to "Inspection", argosui_inspection_path %></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Maintenance <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="#">User</a>
                                            </li>
                                            <li>
                                                <a href="#">Plant</a>
                                            </li>
                                            <li>
                                                <a href="#"> Region</a>
                                            </li>
                                            <li>
                                                <a href="#"> Insepction</a>
                                            </li>
                                        </ul>
                                </li>    
                                
                                <li><%= link_to "Sign In", new_user_session_path %></li>
                                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li> 
                            </ul>
                </div>
             </div>
         </nav>

    

        <!-- Page content -->
    </div>
     

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>




<%=  render 'layouts/nav' %>
<%= bootstrap_flash %>


<!--<div class= 'image'>  
  keep the command from word document or <img src="bg.jpg" width="200" height="40"  alt="">
</div>-->

<div class = 'container'>
<%= yield %>
</div>

</body>
</html>